# Generated by Django 2.2.6 on 2019-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20191201_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
